nelmio_api_doc:
    documentation:
        info:
            title: L'app des Postes Electriques
            description: une application extraordinaire pour récupé
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
